apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-dbpro
  namespace: namespace-dbpro
  labels:
    app: db-pro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbpro1
  template:
    metadata:
      labels:
        app: dbpro1
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          ports:
            - containerPort: 3306
              name: db-port
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mariadb
                  key: password
