apiVersion: v1
kind: Namespace
metadata:
  name: databasespro
  labels:
    name: databasespro
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-dbpro
  namespace: databasespro
  labels:
    app: dbpro1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dbpro1
  template:
    metadata:
      labels:
        app: dbpro1
    spec:
      containers:
        - name: mariadb
          image: mariadb:latest
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: 'Contrasenya'
---
apiVersion: v1
kind: Service
metadata:
  name: my-dbpro
  namespace: databasespro
  labels:
    app: dbpro1
spec:
  type: NodePort
  selector:
    app: dbpro1
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306