---
- name: Configurar kernel para Kubernetes
  hosts: kubernetes
  become: yes
  tasks:
    - name: Crear archivo de configuración de kernel para Kubernetes
      copy:
        dest: /etc/sysctl.d/kubernetes.conf
        content: |
          net.bridge.bridge-nf-call-ip6tables = 1
          net.bridge.bridge-nf-call-iptables = 1
          net.ipv4.ip_forward = 1
    
    - name: Ejecutar el comando sysctl --system
      command: sysctl --system