version: '3'
services:
  db:
    image: mariadb:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == esbcnsrv002]
      restart_policy:
        condition: on-failure
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: "Inicio15"
    ports:
      - "3306:3306"

volumes:
  db_data: