apiVersion: v1
kind: Service
metadata:
  name: service-dbpro
  namespace: namespace-dbpro
  labels:
    app: dbpro1
spec:
  type: NodePort
  selector:
    app: dbpro1
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
