apiVersion: v1
kind: LimitRange
metadata:
  name: minecraft-limits
  namespace: minecraft
spec:
  limits:
  - default:
      cpu: "1"
      memory: "2Gi"
    defaultRequest:
      cpu: "1"
      memory: "1Gi"
    type: Container
