apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  namespace: minecraft
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minecraft
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
      - name: minecraft
        image: "itzg/minecraft-server"
        ports:
        - containerPort: 25565
        env:
        - name: EULA
          value: "TRUE"
        volumeMounts:
        - mountPath: /data
          name: minecraft-storage
      dnsConfig:
        nameservers:
          - 8.8.8.8
          - 8.8.4.4
      volumes:
      - name: minecraft-storage
        persistentVolumeClaim:
          claimName: minecraft-pvc
