apiVersion: v1
kind: Secret
metadata:
  name: smbcreds
  namespace: default
type: Opaque
data:
  username: YWRtaW5pc3RyYWRvcgo=  # Base64 encoded value of 'administrador'
  password: U29wb3J0ZS4xMjMK # Base64 encoded value. 'Soporte.123'