---
# Playbook update ubuntu
- hosts: DockerSwarm
  remote_user: adminsrv
  become: yes
  tasks:
    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes
