---
# Playbook update ubuntu
- hosts: DockerSwarm
  remote_user: adminsrv
  become: yes
  tasks:
    - name: Run the equivalent of "apt-get update" as a separate step
      ansible.builtin.apt:
        update_cache: yes

    - name: Update all packages to their latest version
      ansible.builtin.apt:
        name: "*"
        state: latest

    #- name: Run the equivalent of "apt-get clean" as a separate step
    #  ansible.builtin.apt:
    #    clean: yes

    - name: Remove dependencies that are no longer required
      ansible.builtin.apt:
        autoremove: yes
