- name: Upate cache
  ansible.builtin.apt:
    update-cache: yes
  when:
    - ansible_facts.os_family == "Debian"
- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest
  when:
   - ansible_facts.os_family == "Debian"

